### ISSUE TITLE
Minor: incorrect help on makebigcube

### ISSUE THREAD

**Issue by AstroRipples** [gheald/quocka#24]
Currently, the help for makebigcube.py says that it takes target resolution in arcmin:
`--target TARGET       Target resoltion (circular beam, BMAJ) in arcmin [None].`

Whereas looking in the code itself, it actually takes it in arcsec:
line 255: `new_beam = Beam(major=args.target*u.arcsec,`

**Comment by AlecThomson** [comment]
Now fixed in PR #23
